using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Nuntius.Privacy
{
    /// <summary>
    /// Represents a filter which distributes incoming messages to sets. If the set with included
    /// message contains at least K elements, propagates the message further.
    /// </summary>
    public class KAnonymityFilter<TElement> : EventSourceBase, IEventPropagator
    {
        private readonly Dictionary<int, IKAnonymitySet<TElement>> _sets = new Dictionary<int, IKAnonymitySet<TElement>>();
        private readonly Func<NuntiusMessage, TElement> _mapMessageToElement;
        private readonly Func<TElement, int> _chooseSet;

        /// <summary>
        /// Creates a new instance.
        /// </summary>
        /// <param name="sets">Sets used by k-set algorithm.</param>
        /// <param name="mapMessageToElement">Mapping function from <see cref="NuntiusMessage"/> to <see cref="TElement"/>.
        /// Returned element will be inserted to the set.</param>
        /// <param name="chooseSet">This function have to choose a proper set from the sets
        /// based on passed <see cref="TElement"/>.</param>
        public KAnonymityFilter(IKAnonymitySet<TElement>[] sets, Func<NuntiusMessage, TElement> mapMessageToElement,
            Func<TElement, int> chooseSet)
        {
            if (sets == null || sets.Length == 0) throw new ArgumentException($"Parameter {nameof(sets)} must be array of length at least 1.");
            foreach (var set in sets)
            {
                if (set == null) throw new ArgumentNullException($"One set from {nameof(sets)} was null.");
                if (_sets.ContainsKey(set.Id)) throw new ArgumentException($"There was a set with the same id {set.Id} as a different set.");
                _sets.Add(set.Id, set);
            }
            if (mapMessageToElement == null) throw new ArgumentNullException($"{nameof(mapMessageToElement)} function was null.");
            if (mapMessageToElement == null) throw new ArgumentNullException($"{nameof(chooseSet)} function was null.");

            _mapMessageToElement = mapMessageToElement;
            _chooseSet = chooseSet;
        }

        /// <summary>
        /// Returns a task which represents message processing by the event target.
        /// </summary>
        /// <param name="message">Message to process.</param>
        /// <returns>Task which represents message processing.</returns>
        public Task ProcessMessage(NuntiusMessage message)
        {
            return Task.Factory.StartNew(() =>
            {
                var element = _mapMessageToElement(message);
                var setId = _chooseSet(element);
                IKAnonymitySet<TElement> set;
                if (!_sets.TryGetValue(setId, out set))
                {
                    throw new KeyNotFoundException(
                        $"Element for message {message} returned set id {setId} which was not present between sets.");
                }
                if (set.AddToSet(element)) SafelyInvokeSendEvent(message);
            });
        }

        /// <summary>
        /// Callback which is called when no more messages are generated by the event source.
        /// </summary>
        public void EndProcessing()
        {
            SafelyInvokeEndEvent();
        }
    }
}
