using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Nuntius.Logging
{
    public class FileLogger : EventSourceBase, ILogger, IDisposable, IEventPropagator
    {
        private readonly Func<NuntiusMessage, string> _messageToString;
        private StreamWriter writer;

        public FileLogger(string filePath) : this(filePath, false)
        {
        }

        public FileLogger(string filePath, bool append)
        {
            writer = new StreamWriter(filePath, append);
        }

        public FileLogger(string filePath, bool append, Func<NuntiusMessage, string> messageToString) : this(filePath, append)
        {
            _messageToString = messageToString;
        }

        public void Log(NuntiusMessage message)
        {
            writer.WriteLine(DateTime.Now.ToString("HH:mm:ss"));
            writer.WriteAsync($"Message: {_messageToString?.Invoke(message) ?? message.ToString()} {Environment.NewLine}").Wait();
        }

        /// <summary>
        /// Performs application-defined tasks associated with freeing, releasing, or resetting unmanaged resources.
        /// </summary>
        public void Dispose()
        {
            writer.Dispose();
        }

        /// <summary>
        /// Returns a task which represents message processing by the event target.
        /// </summary>
        /// <param name="message">Message to process.</param>
        /// <returns>Task which represents message processing.</returns>
        public Task ProcessMessage(NuntiusMessage message)
        {
            Log(message);
            return Task.Factory.StartNew(() =>
            {
                SafelyInvokeSendEvent(message);
            });
        }

        /// <summary>
        /// Callback which is called when no more messages are generated by the event source.
        /// </summary>
        public void EndProcessing()
        {
            writer.Dispose();
            SafelyInvokeEndEvent();
        }
    }
}
